apiVersion: v1
kind: Service
metadata:
  name: messaging-app
  namespace: messaging-app
  labels:
    app: messaging-app
    chart: messaging-app-1.0.0
    release: messaging-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: messaging-app
    release: messaging-app
