apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-app-config
  namespace: messaging-app
data:
  FLASK_ENV: "production"
  PORT: "5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: messaging-app-secrets
  namespace: messaging-app
type: Opaque
data:
  # Base64 encoded secrets (add as needed)
  # echo -n "your-secret" | base64
  DATABASE_URL: ""  # Add if using external database
